version: "3"

tasks:
  generate-server:
    desc: Generates the server code.
    cmds:
      - cd server-gen && oapi-codegen --config=server.cfg.yaml ../swagger.yaml
      - cd server-gen && oapi-codegen --config=models.cfg.yaml ../swagger.yaml
    preconditions:
      - rm -rf server-gen/*.go