version: "3"

tasks:
  generate-server:
    desc: Generates the server code.
    cmds:
      - cd api && oapi-codegen --config=server.cfg.yaml swagger.yaml
      - cd api && oapi-codegen --config=models.cfg.yaml swagger.yaml
    preconditions:
      - rm -rf api/*.gen.go